<a href="https://colab.research.google.com/github/JMC110/Homework_0/blob/master/Einsum%2BComputations_on_Arrays1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c = np.arange(6).reshape(2,3)

In [2]:
np.einsum('ii', a)
np.einsum(a, [0,0])
np.trace(a)

60

In [3]:
np.einsum('ii->i', a)

array([ 0,  6, 12, 18, 24])

In [4]:
np.einsum(a, [0,0], [0])

array([ 0,  6, 12, 18, 24])

In [5]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [6]:
np.sum(a, axis=1)

array([ 10,  35,  60,  85, 110])

In [7]:
np.einsum('...j->...', a)

array([ 10,  35,  60,  85, 110])

In [8]:
np.einsum(a, [Ellipsis,1], [Ellipsis])

array([ 10,  35,  60,  85, 110])

In [9]:
np.einsum('ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [10]:
np.einsum('ij->ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [11]:
np.einsum('i,i', b, b)

30

In [12]:
np.einsum('ij,j', a, b)

array([ 30,  80, 130, 180, 230])

In [13]:
np.einsum('..., ...', 3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [14]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', a, b)

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [15]:
np.einsum(a, [0,1,2], b, [1,0,3], [2,3])

array([[4400., 4730.],
       [4532., 4874.],
       [4664., 5018.],
       [4796., 5162.],
       [4928., 5306.]])

In [16]:
a = np.arange(6).reshape((3,2))
b = np.arange(12).reshape((4,3))
np.einsum('ki,jk->ij', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

Computation on Arrays-**Broadcasting**

In [17]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [18]:
a+5

array([5, 6, 7])

In [19]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [21]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [22]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [0]:
M = np.ones((2, 3))
a = np.arange(3)

In [24]:
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [0]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

In [26]:
a

array([[0],
       [1],
       [2]])

In [27]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [28]:
a[:, np.newaxis].shape

(3, 1, 1)

In [29]:
M + a[:, np.newaxis]

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.]]])